# Données

## Importation des packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import requests
from bs4 import BeautifulSoup
import os
import s3fs
import ast

## Lecture des fichiers movies_metadata.csv et credits.csv

Les données de movies_metadata.csv et credits.csv sont des données trouvées sur Kaggle qui centralisent des informations diverses sur des films sortis avant juillet 2017. 

Les variables de movies_metadata.csv sont :
adult : signification de la varible non connue
belongs to collection : si le film appartient à une série de film, la variable renseigne les films faisant partie de cette série
budget : budget du film
genres : genres du film
homepage : lien vers le site officiel du film s'il y en a un
id et imdb_id : identifiants du film
original_language : langue originale du film
original_title : titre original du film
overview : résumé du film
popularity : popularité du film sur IMDB
poster_path : lien vers l'affiche du film
production_countries : pays de production du film
production_companies : compagnies de production du film
release_date : date de sortie du film
revenue : recettes du film
runtime : durée du film
spoken_languages : langues parlées dans le film en version originale
status : si le film est sorti, prévu, annulé, en production etc
tagline : catchphrase du film
title : titre anglophone du film
video : False si le film est sorti au cinéma, True s'il est sorti directement sur Internet et qu'il n'a pas été diffusé au cinéma

Les variables de credits.csv sont :
cast : casting du film sous forme de liste de dictionnaires
crew : équipe du film sous forme de liste de dictionnaires

Nous souhaitons à partir de ces données prédire la note de nouveaux films, voir quelles sont les variables les plus décisives pour prédire si un film sera ien reçu par le public et ainsi remarquer (ou non) la prévisibilité du succès d'un film.

Nous pourrons pondérer l'erreur de prévision avec la variable vote_count et faire de la classification non supervisée dans les stats descriptives

In [2]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_KEY_S3 = '/movies_metadata.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    data_movies = pd.read_csv(file_in,sep=',', header=0)

/tmp/ipykernel_13749/2309787388.py:9: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data_movies = pd.read_csv(file_in,sep=',', header=0)

In [3]:
FILE_KEY_S3 = '/credits.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    data_credits = pd.read_csv(file_in,sep=',', header=0)

Après première exploration des données, nous avons décidé d'enlever les variables suivantes : adult, homepage, overview, popularity, poster_path, spoken_languages et tagline. En effet, la variable adult présente presque toujours la modalité False et semble avoir peu d'intérêt. La variable homepage renseigne le lien vers le site officiel du film s'il y en a un. La variable overview contient les résumés des films du dataframe, ce qui peut être intéressant à exploiter mais nous avons décidé de ne pas le faire. La variable popularity est la popularité du film sur IMDB au moment où les données ont été extraites, c'est donc une variable qui n'est pas statique et qui est calculée directement par IMDB d'une façon que nous ignorons donc nous ne souhaitons pas la prendre en compte. La variable poster_path indique le lien vers l'affiche du film, nous n'en avons pas besoin. La variable spoken_languages indique les langues parlées durant le film en version originale, nous considérons que cette variable est redondante par rapport à la variable original_language. Enfin la variable tagline indique la catchphrase du film, ce qui est à nos yeux peu utile également.

Nous allons retraiter certaines variables. Par exemple, la variable belongs_to_collection sera transformée en booléen (1 si le film correspond à une série de films, 0 sinon) à laquelle nous ajouterons une variable avec le nombre de films précédents de la série ainsi que la note du film précédent. La variable genres sera décomposée en plusieurs variables genre_1, genre_2 etc. Ce genre de décomposition sera également nécessaire pour les variables production_countries et production_companies

Les variables budget et runtime présentent des valeurs manquantes, que nous allons essayer de compléter avec du web scraping.

Nous allons nous concentrer sur les films qui sont déjà sortis en salle (status = Released et video=False)

Les données du fichier credits.csv vont nous permettre d'ajouter les acteurs principaux et le réalisateur du film à notre jeu de données. Nous souhaitons ajouter des variables relatives à la popularité des acteurs et du réalisateur via du web scraping.

In [4]:
data_movies.original_language.value_counts()

original_language
en      32269
fr       2438
it       1529
ja       1350
de       1080
        ...
sm          1
82.0        1
hy          1
lb          1
si          1
Name: count, Length: 92, dtype: int64

In [26]:
data_movies_df = data_movies[data_movies['video'] == False]
data_movies_df = data_movies_df[data_movies_df['status'] == 'Released']
data_movies_df = data_movies_df.drop(columns=['adult', 'homepage', 'overview', 'popularity', 'poster_path', 'tagline', 'status', 'video'])
data_movies_df = data_movies_df.dropna(subset= ['release_date'])
data_movies_df = data_movies_df.dropna(subset= ['imdb_id'])
data_movies_df = data_movies_df.dropna(subset= ['original_language'])

In [6]:
data_movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44825 entries, 0 to 45465
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4460 non-null   object
 1   budget                 44825 non-null  object
 2   genres                 44825 non-null  object
 3   id                     44825 non-null  object
 4   imdb_id                44825 non-null  object
 5   original_language      44825 non-null  object
 6   original_title         44825 non-null  object
 7   production_companies   44825 non-null  object
 8   production_countries   44825 non-null  object
 9   release_date           44825 non-null  object
 10  revenue                44825 non-null  float64
 11  runtime                44588 non-null  float64
 12  title                  44825 non-null  object
 13  vote_average           44825 non-null  float64
 14  vote_count             44825 non-null  float64
dtypes: float64(4), object(11)
memory usage: 5.5+ MB

In [7]:
missing_percentage = data_movies_df.isna().sum()

print('MISSING VALUES :')
if missing_percentage[missing_percentage != 0].empty:
    print('No')
else:
    print(missing_percentage[missing_percentage != 0].sort_values(ascending=False))

MISSING VALUES :
belongs_to_collection    40365
runtime                    237
dtype: int64

On ajoute au dataframe les différents url wikipédia possibles pour un film (selon le nom du film, il faut parfois ajouter film ou film + année de sortie à l'url wikipédia pour tomber sur la bonne page wiki)

In [27]:
url_wikipedia_fr = "https://fr.wikipedia.org/wiki/"
url_wikipedia_en = "https://en.wikipedia.org/wiki/"
data_movies_df['url'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_")
data_movies_df['url_film'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_") + "_(film)"
data_movies_df['release_year'] = data_movies_df.release_date.str[:4]
data_movies_df['url_film_date'] = url_wikipedia_en + data_movies_df.title.str.replace(" ", "_") + "_(film,_" + data_movies_df.release_year + ")"
data_movies_df['id'] = pd.to_numeric(data_movies_df['id'])

On joint les dataframes movies et credits pour ajouter le casting et l'équipe du film.

In [28]:
data_movies_credits = data_movies_df.merge(data_credits, left_on='id', right_on='id')
data_movies_credits

,belongs_to_collection,budget,genres,id,imdb_id,original_language,original_title,production_companies,production_countries,release_date,...,spoken_languages,title,vote_average,vote_count,url,url_film,release_year,url_film_date,cast,crew
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,Toy Story,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Toy Story,7.7,5415.0,https://en.wikipedia.org/wiki/Toy_Story,https://en.wikipedia.org/wiki/Toy_Story_(film),1995,"https://en.wikipedia.org/wiki/Toy_Story_(film,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,Jumanji,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Jumanji,6.9,2413.0,https://en.wikipedia.org/wiki/Jumanji,https://en.wikipedia.org/wiki/Jumanji_(film),1995,"https://en.wikipedia.org/wiki/Jumanji_(film,_1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,Grumpier Old Men,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Grumpier Old Men,6.5,92.0,https://en.wikipedia.org/wiki/Grumpier_Old_Men,https://en.wikipedia.org/wiki/Grumpier_Old_Men...,1995,https://en.wikipedia.org/wiki/Grumpier_Old_Men...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,Waiting to Exhale,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Waiting to Exhale,6.1,34.0,https://en.wikipedia.org/wiki/Waiting_to_Exhale,https://en.wikipedia.org/wiki/Waiting_to_Exhal...,1995,https://en.wikipedia.org/wiki/Waiting_to_Exhal...,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,Father of the Bride Part II,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Father of the Bride Part II,5.7,173.0,https://en.wikipedia.org/wiki/Father_of_the_Br...,https://en.wikipedia.org/wiki/Father_of_the_Br...,1995,https://en.wikipedia.org/wiki/Father_of_the_Br...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44893,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,tt0102797,en,Robin Hood,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Robin Hood,5.7,26.0,https://en.wikipedia.org/wiki/Robin_Hood,https://en.wikipedia.org/wiki/Robin_Hood_(film),1991,https://en.wikipedia.org/wiki/Robin_Hood_(film...,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de..."
44894,NaN,0,"[{'id': 18, 'name': 'Drama'}]",111109,tt2028550,tl,Siglo ng Pagluluwal,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,...,"[{'iso_639_1': 'tl', 'name': ''}]",Century of Birthing,9.0,3.0,https://en.wikipedia.org/wiki/Century_of_Birthing,https://en.wikipedia.org/wiki/Century_of_Birth...,2011,https://en.wikipedia.org/wiki/Century_of_Birth...,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de..."
44895,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,tt0303758,en,Betrayal,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Betrayal,3.8,6.0,https://en.wikipedia.org/wiki/Betrayal,https://en.wikipedia.org/wiki/Betrayal_(film),2003,"https://en.wikipedia.org/wiki/Betrayal_(film,_...","[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de..."
44896,NaN,0,[],227506,tt0008536,en,Satana likuyushchiy,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,...,[],Satan Triumphant,0.0,0.0,https://en.wikipedia.org/wiki/Satan_Triumphant,https://en.wikipedia.org/wiki/Satan_Triumphant...,1917,https://en.wikipedia.org/wiki/Satan_Triumphant...,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de..."
44897,NaN,0,[],461257,tt6980792,en,Queerama,[],"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",2017-06-09,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Queerama,0.0,0.0,https://en.wikipedia.org/wiki/Queerama,https://en.wikipedia.org/wiki/Queerama_(film),2017,"https://en.wikipedia.org/wiki/Queerama_(film,_...",[],"[{'credit_id': '593e676c92514105b702e68e', 'de..."

On retraite les colonnes cast et crew pour que Python les reconnaissent en tant que liste de dictionnaires.

In [29]:
data_movies_credits['cast'] = data_movies_credits['cast'].apply(ast.literal_eval)
data_movies_credits['crew'] = data_movies_credits['crew'].apply(ast.literal_eval)

On ajoute les colonnes correspondant aux 4 acteurs principaux du film et une colonne pour le réalisateur du film.

In [30]:
data_movies_credits['acteur_1'] = data_movies_credits['cast'].apply(
    lambda lst: lst[0]['name'] if isinstance(lst, list) and len(lst) > 0 else None
)
data_movies_credits['acteur_2'] = data_movies_credits['cast'].apply(
    lambda lst: lst[1]['name'] if isinstance(lst, list) and len(lst) > 1 else None
)
data_movies_credits['acteur_3'] = data_movies_credits['cast'].apply(
    lambda lst: lst[2]['name'] if isinstance(lst, list) and len(lst) > 2 else None
)
data_movies_credits['acteur_4'] = data_movies_credits['cast'].apply(
    lambda lst: lst[3]['name'] if isinstance(lst, list) and len(lst) > 3 else None
)

data_movies_credits['realisateur'] = data_movies_credits['crew'].apply(
    lambda lst: lst['job' == 'Director']['name'] if isinstance(lst, list) and len(lst) > 0 else None
)

On enlève les lignes où il n'y a pas d'acteurs.

In [31]:
data_movies_credits = data_movies_credits[data_movies_credits['cast'].apply(lambda x: len(x) != 0)]
data_movies_credits

,belongs_to_collection,budget,genres,id,imdb_id,original_language,original_title,production_companies,production_countries,release_date,...,url_film,release_year,url_film_date,cast,crew,acteur_1,acteur_2,acteur_3,acteur_4,realisateur
0,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,Toy Story,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,...,https://en.wikipedia.org/wiki/Toy_Story_(film),1995,"https://en.wikipedia.org/wiki/Toy_Story_(film,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",Tom Hanks,Tim Allen,Don Rickles,Jim Varney,John Lasseter
1,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,Jumanji,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,...,https://en.wikipedia.org/wiki/Jumanji_(film),1995,"https://en.wikipedia.org/wiki/Jumanji_(film,_1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",Robin Williams,Jonathan Hyde,Kirsten Dunst,Bradley Pierce,Larry J. Franco
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,Grumpier Old Men,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,https://en.wikipedia.org/wiki/Grumpier_Old_Men...,1995,https://en.wikipedia.org/wiki/Grumpier_Old_Men...,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",Walter Matthau,Jack Lemmon,Ann-Margret,Sophia Loren,Howard Deutch
3,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,Waiting to Exhale,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,...,https://en.wikipedia.org/wiki/Waiting_to_Exhal...,1995,https://en.wikipedia.org/wiki/Waiting_to_Exhal...,"[{'cast_id': 1, 'character': 'Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",Whitney Houston,Angela Bassett,Loretta Devine,Lela Rochon,Forest Whitaker
4,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,Father of the Bride Part II,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-02-10,...,https://en.wikipedia.org/wiki/Father_of_the_Br...,1995,https://en.wikipedia.org/wiki/Father_of_the_Br...,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",Steve Martin,Diane Keaton,Martin Short,Kimberly Williams-Paisley,Alan Silvestri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44892,NaN,0,"[{'id': 878, 'name': 'Science Fiction'}]",222848,tt0112613,en,Caged Heat 3000,"[{'name': 'Concorde-New Horizons', 'id': 4688}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-01-01,...,https://en.wikipedia.org/wiki/Caged_Heat_3000_...,1995,https://en.wikipedia.org/wiki/Caged_Heat_3000_...,"[{'cast_id': 1, 'character': 'Kira (as Cassand...","[{'credit_id': '5757f36ac3a3687d6f000e8a', 'de...",Lisa Boyle,Kena Land,Zaneta Polard,Don Yanan,Roger Corman
44893,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",30840,tt0102797,en,Robin Hood,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",1991-05-13,...,https://en.wikipedia.org/wiki/Robin_Hood_(film),1991,https://en.wikipedia.org/wiki/Robin_Hood_(film...,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",Patrick Bergin,Uma Thurman,David Morrissey,Jürgen Prochnow,John Irvin
44894,NaN,0,"[{'id': 18, 'name': 'Drama'}]",111109,tt2028550,tl,Siglo ng Pagluluwal,"[{'name': 'Sine Olivia', 'id': 19653}]","[{'iso_3166_1': 'PH', 'name': 'Philippines'}]",2011-11-17,...,https://en.wikipedia.org/wiki/Century_of_Birth...,2011,https://en.wikipedia.org/wiki/Century_of_Birth...,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",Angel Aquino,Perry Dizon,Hazel Orencio,Joel Torre,Lav Diaz
44895,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",67758,tt0303758,en,Betrayal,"[{'name': 'American World Pictures', 'id': 6165}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2003-08-01,...,https://en.wikipedia.org/wiki/Betrayal_(film),2003,"https://en.wikipedia.org/wiki/Betrayal_(film,_...","[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",Erika Eleniak,Adam Baldwin,Julie du Page,James Remar,Mark L. Lester
44896,NaN,0,[],227506,tt0008536,en,Satana likuyushchiy,"[{'name': 'Yermoliev', 'id': 88753}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",1917-10-21,...,https://en.wikipedia.org/wiki/Satan_Triumphant...,1917,https://en.wikipedia.org/wiki/Satan_Triumphant...,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",Iwan Mosschuchin,Nathalie Lissenko,Pavel Pavlov,Aleksandr Chabrov,Yakov Protazanov

In [49]:
data=data_movies_credits

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
}

Fonction pour trouver le budget d'un film avec l'url wikipédia

In [50]:
def extraire_budget_depuis_wikipedia(url):
    try:
        # Charger la page
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        # Parser le HTML
        soup = BeautifulSoup(response.content, 'html.parser')

        # Trouver l'infobox (il peut y avoir plusieurs classes, mais 'infobox' est souvent commun)
        infobox = soup.find('table', class_='infobox')

        if infobox is None:
            return None  # Pas d'infobox trouvée

        # Chercher les lignes de l'infobox
        rows = infobox.find_all('tr')

        for row in rows:
            header = row.find('th')
            if header and 'budget' in header.get_text(strip=True).lower():
                # Trouver la cellule contenant la valeur
                value_cell = row.find('td')
                if value_cell:
                    return value_cell.get_text(separator=" ", strip=True)

        return None  # Pas de ligne contenant "budget"

    except Exception as e:
        print(f"Erreur lors du traitement de {url}: {e}")
        return None

In [52]:
data['budget_2'] = data['url'].apply(extraire_budget_depuis_wikipedia)

Erreur lors du traitement de https://en.wikipedia.org/wiki/How_To_Make_An_American_Quilt: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/How_To_Make_An_American_Quilt
Erreur lors du traitement de https://en.wikipedia.org/wiki/Nico_Icon: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Nico_Icon
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Neverending_Story_III:_Escape_from_Fantasia: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Neverending_Story_III:_Escape_from_Fantasia
Erreur lors du traitement de https://en.wikipedia.org/wiki/Jupiter's_Wife: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Jupiter's_Wife
Erreur lors du traitement de https://en.wikipedia.org/wiki/Sonic_Outlaws: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Sonic_Outlaws
Erreur lors du traitement de https://en.wikipedia.org/wiki/Free_Willy_2_-_The_Adventure_Home: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Free_Willy_2_-_The_Adventure_Home
Erreur lors du traitement de https://en.wikipedia.org/wiki/New_York_Cop: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/New_York_Cop
Erreur lors du traitement de https://en.wikipedia.org/wiki/Beyond_Bedlam: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Beyond_Bedlam
Erreur lors du traitement de https://en.wikipedia.org/wiki/Nemesis_2_-_Nebula: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Nemesis_2_-_Nebula
Erreur lors du traitement de https://en.wikipedia.org/wiki/Boys_Life:_Three_Stories_of_Love,_Lust,_and_Liberation: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Boys_Life:_Three_Stories_of_Love,_Lust,_and_Liberation
Erreur lors du traitement de https://en.wikipedia.org/wiki/Dos_Crímenes: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Dos_Cr%C3%ADmenes
Erreur lors du traitement de https://en.wikipedia.org/wiki/Brother_Minister:_The_Assassination_of_Malcolm_X: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Brother_Minister:_The_Assassination_of_Malcolm_X
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Man_without_a_Face: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Man_without_a_Face
Erreur lors du traitement de https://en.wikipedia.org/wiki/Tough_and_Deadly: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Tough_and_Deadly
Erreur lors du traitement de https://en.wikipedia.org/wiki/Roula: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Roula
Erreur lors du traitement de https://en.wikipedia.org/wiki/Peanuts_–_Die_Bank_zahlt_alles: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Peanuts_%E2%80%93_Die_Bank_zahlt_alles
Erreur lors du traitement de https://en.wikipedia.org/wiki/Happy_Weekend: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Happy_Weekend
Erreur lors du traitement de https://en.wikipedia.org/wiki/Und_keiner_weint_mir_nach: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Und_keiner_weint_mir_nach
Erreur lors du traitement de https://en.wikipedia.org/wiki/My_Mother's_Courage: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/My_Mother's_Courage
Erreur lors du traitement de https://en.wikipedia.org/wiki/Bloodsport_II: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Bloodsport_II
Erreur lors du traitement de https://en.wikipedia.org/wiki/Hostile_Intentions: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Hostile_Intentions
Erreur lors du traitement de https://en.wikipedia.org/wiki/Tigrero:_A_Film_That_Was_Never_Made: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Tigrero:_A_Film_That_Was_Never_Made
Erreur lors du traitement de https://en.wikipedia.org/wiki/To_Cross_the_Rubicon: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/To_Cross_the_Rubicon
Erreur lors du traitement de https://en.wikipedia.org/wiki/Priest_Daens: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Priest_Daens
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Haunted_World_of_Edward_D._Wood,_Jr.: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Haunted_World_of_Edward_D._Wood,_Jr.
Erreur lors du traitement de https://en.wikipedia.org/wiki/Brothers_in_Trouble: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Brothers_in_Trouble
Erreur lors du traitement de https://en.wikipedia.org/wiki/My_Life_and_Times_With_Antonin_Artaud: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/My_Life_and_Times_With_Antonin_Artaud
Erreur lors du traitement de https://en.wikipedia.org/wiki/Diebinnen: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Diebinnen
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Story_of_Xinghua: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Story_of_Xinghua
Erreur lors du traitement de https://en.wikipedia.org/wiki/Lover's_Knot: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Lover's_Knot
Erreur lors du traitement de https://en.wikipedia.org/wiki/L'associé: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/L'associ%C3%A9
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Leopard_Son: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Leopard_Son
Erreur lors du traitement de https://en.wikipedia.org/wiki/Charm's__Incidents: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Charm%27s_Incidents
Erreur lors du traitement de https://en.wikipedia.org/wiki/Entertaining_Angels_-_The_Dorothy_Day_Story: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Entertaining_Angels_-_The_Dorothy_Day_Story
Erreur lors du traitement de https://en.wikipedia.org/wiki/Snowriders: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Snowriders
Erreur lors du traitement de https://en.wikipedia.org/wiki/JLG/JLG:_Self-Portrait_in_December: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/JLG/JLG:_Self-Portrait_in_December
Erreur lors du traitement de https://en.wikipedia.org/wiki/Paris_Was_a_Woman: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Paris_Was_a_Woman
Erreur lors du traitement de https://en.wikipedia.org/wiki/Message_to_Love:_The_Isle_of_Wight_Festival: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Message_to_Love:_The_Isle_of_Wight_Festival
Erreur lors du traitement de https://en.wikipedia.org/wiki/Kama_Sutra_-_A_Tale_of_Love: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Kama_Sutra_-_A_Tale_of_Love
Erreur lors du traitement de https://en.wikipedia.org/wiki/To_Have_(Or_Not): 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/To_Have_(Or_Not)
Erreur lors du traitement de https://en.wikipedia.org/wiki/MURDER_and_murder: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/MURDER_and_murder
Erreur lors du traitement de https://en.wikipedia.org/wiki/Telling_Lies_In_America: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Telling_Lies_In_America
Erreur lors du traitement de https://en.wikipedia.org/wiki/Alien_Escape: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Alien_Escape
Erreur lors du traitement de https://en.wikipedia.org/wiki/Man_of_Her_Dreams: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Man_of_Her_Dreams
Erreur lors du traitement de https://en.wikipedia.org/wiki/Other_Voices_Other_Rooms: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Other_Voices_Other_Rooms
Erreur lors du traitement de https://en.wikipedia.org/wiki/Time_Tracers: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Time_Tracers
Erreur lors du traitement de https://en.wikipedia.org/wiki/Men_of_Means: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Men_of_Means
Erreur lors du traitement de https://en.wikipedia.org/wiki/An_Alan_Smithee_Film:_Burn,_Hollywood,_Burn: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/An_Alan_Smithee_Film:_Burn,_Hollywood,_Burn
Erreur lors du traitement de https://en.wikipedia.org/wiki/Herbie_Goes_To_Monte_Carlo: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Herbie_Goes_To_Monte_Carlo
Erreur lors du traitement de https://en.wikipedia.org/wiki/Hot_Lead_&_Cold_Feet: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Hot_Lead_&_Cold_Feet
Erreur lors du traitement de https://en.wikipedia.org/wiki/Henry_II,_Portrait_of_a_Serial_Killer: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Henry_II,_Portrait_of_a_Serial_Killer
Erreur lors du traitement de https://en.wikipedia.org/wiki/National_Lampoon’s_European_Vacation: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/National_Lampoon%E2%80%99s_European_Vacation
Erreur lors du traitement de https://en.wikipedia.org/wiki/Iron_Eagle_III: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Iron_Eagle_III
Erreur lors du traitement de https://en.wikipedia.org/wiki/Hamlet_from_the_Lunt-Fontanne_Theatre: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Hamlet_from_the_Lunt-Fontanne_Theatre
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Spiders_-_The_Golden_Sea: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Spiders_-_The_Golden_Sea
Erreur lors du traitement de https://en.wikipedia.org/wiki/Plunkett_&_MacLeane: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Plunkett_&_MacLeane
Erreur lors du traitement de https://en.wikipedia.org/wiki/L'ennui: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/L'ennui
Erreur lors du traitement de https://en.wikipedia.org/wiki/Man_Of_The_Century: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Man_Of_The_Century
Erreur lors du traitement de https://en.wikipedia.org/wiki/Portraits_Chinois: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Portraits_Chinois
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Incredibly_True_Adventure_of_Two_Girls_In_Love: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Incredibly_True_Adventure_of_Two_Girls_In_Love
Erreur lors du traitement de https://en.wikipedia.org/wiki/Experience_Preferred...But_Not_Essential: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Experience_Preferred...But_Not_Essential
Erreur lors du traitement de https://en.wikipedia.org/wiki/Pokémon:_The_First_Movie:_Mewtwo_Strikes_Back: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Pok%C3%A9mon:_The_First_Movie:_Mewtwo_Strikes_Back
Erreur lors du traitement de https://en.wikipedia.org/wiki/Where's_Marlowe?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Where's_Marlowe
Erreur lors du traitement de https://en.wikipedia.org/wiki/Santitos: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Santitos
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Fantastic_Night: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Fantastic_Night
Erreur lors du traitement de https://en.wikipedia.org/wiki/Date_With_an_Angel: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Date_With_an_Angel
Erreur lors du traitement de https://en.wikipedia.org/wiki/Something_For_Everyone: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Something_For_Everyone
Erreur lors du traitement de https://en.wikipedia.org/wiki/Death_Wish_5:_The_Face_of_Death: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Death_Wish_5:_The_Face_of_Death
Erreur lors du traitement de https://en.wikipedia.org/wiki/Here_On_Earth: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Here_On_Earth
Erreur lors du traitement de https://en.wikipedia.org/wiki/Where_the_Money_is: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Where_the_Money_is
Erreur lors du traitement de https://en.wikipedia.org/wiki/Smiling_Fish_&_Goat_On_Fire: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Smiling_Fish_&_Goat_On_Fire
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Nibelungs,_Tale_1:_Siegfried: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Nibelungs,_Tale_1:_Siegfried
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Myth_Of_Fingerprints: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Myth_Of_Fingerprints
Erreur lors du traitement de https://en.wikipedia.org/wiki/Puppet_Master_III_Toulon's_Revenge: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Puppet_Master_III_Toulon's_Revenge
Erreur lors du traitement de https://en.wikipedia.org/wiki/Porky's_3:_Revenge: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Porky's_3:_Revenge
Erreur lors du traitement de https://en.wikipedia.org/wiki/Everything_You_Always_Wanted_to_Know_About_Sex_*But_Were_Afraid_to_Ask: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Everything_You_Always_Wanted_to_Know_About_Sex_*But_Were_Afraid_to_Ask
Erreur lors du traitement de https://en.wikipedia.org/wiki/Margaret_Cho:_I'm_the_One_That_I_Want: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Margaret_Cho:_I'm_the_One_That_I_Want
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Ballad_of_Ramblin'_Jack: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Ballad_of_Ramblin'_Jack
Erreur lors du traitement de https://en.wikipedia.org/wiki/Dude,_Where’s_My_Car?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Dude,_Where%E2%80%99s_My_Car
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_St__Francisville_Experiment: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_St_Francisville_Experiment
Erreur lors du traitement de https://en.wikipedia.org/wiki/Harry,_He's_Here_To_Help: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Harry,_He's_Here_To_Help
Erreur lors du traitement de https://en.wikipedia.org/wiki/Me,_You,_Them: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Me,_You,_Them
Erreur lors du traitement de https://en.wikipedia.org/wiki/Elvis_That's_the_Way_It_Is: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Elvis_That's_the_Way_It_Is
Erreur lors du traitement de https://en.wikipedia.org/wiki/Pokémon:_Spell_of_the_Unknown: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Pok%C3%A9mon:_Spell_of_the_Unknown
Erreur lors du traitement de https://en.wikipedia.org/wiki/Pokémon:_Spell_of_the_Unknown: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Pok%C3%A9mon:_Spell_of_the_Unknown
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Low_Down: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Low_Down
Erreur lors du traitement de https://en.wikipedia.org/wiki/Funny_Felix: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Funny_Felix
Erreur lors du traitement de https://en.wikipedia.org/wiki/C.H.U.D._II:_Bud_the_Chud: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/C.H.U.D._II:_Bud_the_Chud
Erreur lors du traitement de https://en.wikipedia.org/wiki/Stepfather_II:_Make_Room_For_Daddy: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Stepfather_II:_Make_Room_For_Daddy
Erreur lors du traitement de https://en.wikipedia.org/wiki/La_Cage_aux_folles_II: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/La_Cage_aux_folles_II
Erreur lors du traitement de https://en.wikipedia.org/wiki/Va_Savoir_(Who_Knows?): 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Va_Savoir_(Who_Knows?)
Erreur lors du traitement de https://en.wikipedia.org/wiki/Won't_Anybody_Listen: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Won't_Anybody_Listen
Erreur lors du traitement de https://en.wikipedia.org/wiki/Hail_Columbia!: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Hail_Columbia!
Erreur lors du traitement de https://en.wikipedia.org/wiki/Hell_Up_In_Harlem: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Hell_Up_In_Harlem
Erreur lors du traitement de https://en.wikipedia.org/wiki/What_Time_Is_It_There?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/What_Time_Is_It_There
Erreur lors du traitement de https://en.wikipedia.org/wiki/StageFright:_Aquarius: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/StageFright:_Aquarius
Erreur lors du traitement de https://en.wikipedia.org/wiki/Who's_Singin'_Over_There?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Who's_Singin'_Over_There
Erreur lors du traitement de https://en.wikipedia.org/wiki/Sällskapsresan_-_eller_finns_det_svenskt_kaffe_på_grisfesten?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/S%C3%A4llskapsresan_-_eller_finns_det_svenskt_kaffe_p%C3%A5_grisfesten
Erreur lors du traitement de https://en.wikipedia.org/wiki/Teheran_'43: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Teheran_'43
Erreur lors du traitement de https://en.wikipedia.org/wiki/In_The_Winter_Dark: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/In_The_Winter_Dark
Erreur lors du traitement de https://en.wikipedia.org/wiki/30_YEARS_TO_LIFE: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/30_YEARS_TO_LIFE
Erreur lors du traitement de https://en.wikipedia.org/wiki/National_Lampoon’s_Van_Wilder: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/National_Lampoon%E2%80%99s_Van_Wilder
Erreur lors du traitement de https://en.wikipedia.org/wiki/Who_Is_Cletis_Tout?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Who_Is_Cletis_Tout
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Château: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Ch%C3%A2teau
Erreur lors du traitement de https://en.wikipedia.org/wiki/City_By_The_Sea: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/City_By_The_Sea
Erreur lors du traitement de https://en.wikipedia.org/wiki/Betty_Fisher_and_Other_Stories: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Betty_Fisher_and_Other_Stories
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Mesmerist: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Mesmerist
Erreur lors du traitement de https://en.wikipedia.org/wiki/Ernest_In_The_Army: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Ernest_In_The_Army
Erreur lors du traitement de https://en.wikipedia.org/wiki/The_Young_Unknowns: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/The_Young_Unknowns
Erreur lors du traitement de https://en.wikipedia.org/wiki/Who_Pulled_the_Plug?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Who_Pulled_the_Plug
Erreur lors du traitement de https://en.wikipedia.org/wiki/All_The_Queen's_Men: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/All_The_Queen's_Men
Erreur lors du traitement de https://en.wikipedia.org/wiki/Do_You_Remember_Dolly_Bell?: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Do_You_Remember_Dolly_Bell
Erreur lors du traitement de https://en.wikipedia.org/wiki/Better_Housekeeping: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Better_Housekeeping

/tmp/ipykernel_13749/3722422632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['budget_2'] = data['url'].apply(extraire_budget_depuis_wikipedia)

In [61]:
data[['title','budget', 'budget_2']].head(500)

,title,budget,budget_2
0,Toy Story,30000000,$30 million [ 2 ]
1,Jumanji,65000000,$65 million [ 1 ]
2,Grumpier Old Men,0,$25 million
3,Waiting to Exhale,16000000,$16 million
4,Father of the Bride Part II,0,<$40 million [ 1 ]
5,Heat,60000000,None
6,Sabrina,58000000,None
7,Tom and Huck,0,None
8,Sudden Death,35000000,None
9,GoldenEye,58000000,$60 million [ 3 ]
10,The American President,62000000,$62 million [ 2 ]
11,Dracula: Dead and Loving It,0,$30 million
12,Balto,0,None
13,Nixon,44000000,None
14,Cutthroat Island,98000000,$92–115 million [ 3 ] [ 4 ] [ 5 ]
15,Casino,52000000,None
16,Sense and Sensibility,16500000,None
17,Four Rooms,4000000,$4 million
18,Ace Ventura: When Nature Calls,30000000,$30 million [ 1 ]
19,Money Train,60000000,$68 million [ 1 ]
20,Get Shorty,30250000,None
21,Copycat,0,None
22,Assassins,50000000,None
23,Powder,0,None
24,Leaving Las Vegas,3600000,$3.5–4 million [ 3 ] [ 4 ]
25,Othello,0,None
26,Now and Then,12000000,None
27,Persuasion,0,None
28,The City of Lost Children,18000000,$18 million [ 4 ]
29,Shanghai Triad,0,None
30,Dangerous Minds,0,$23 million [ 2 ]
31,Twelve Monkeys,29500000,$29 million [ 1 ]
32,Wings of Courage,0,$20 million [ 1 ]
33,Babe,30000000,None
34,Carrington,0,None
35,Dead Man Walking,11000000,None
36,Across the Sea of Time,0,None
37,It Takes Two,0,None
38,Clueless,12000000,$12 million [ 2 ]
39,"Cry, the Beloved Country",0,None
40,Richard III,0,None
41,Dead Presidents,10000000,$10 million
42,Restoration,19000000,None
43,Mortal Kombat,18000000,None
44,To Die For,20000000,$20 million [ 1 ]
45,How To Make An American Quilt,10000000,None
46,Se7en,33000000,None
47,Pocahontas,55000000,None
48,When Night Is Falling,0,None
49,The Usual Suspects,6000000,$6 million [ 3 ]
50,Guardian Angel,0,None
51,Mighty Aphrodite,15000000,$15 million [ 2 ]
52,Lamerica,0,None
53,The Big Green,0,$12 million
54,Georgia,0,None
55,Kids of the Round Table,0,None
56,Home for the Holidays,0,None
57,The Postman,0,None
58,The Confessional,0,None
59,The Indian in the Cupboard,45000000,None
60,Eye for an Eye,20000000,None
61,Mr. Holland's Opus,0,$31 million [ 2 ]
62,Don't Be a Menace to South Central While Drink...,0,$3.8 million
63,Two If by Sea,0,None
64,Bio-Dome,15000000,$8.5 million [ 1 ]
65,Lawnmower Man 2: Beyond Cyberspace,0,$15 million [ 1 ] [ 2 ]
66,Two Bits,0,None
67,French Twist,0,None
68,Friday,3500000,None
69,From Dusk Till Dawn,19000000,$19 million [ 3 ]
70,Fair Game,50000000,None
71,Kicking and Screaming,0,None
72,Les Miserables,0,None
73,Bed of Roses,0,None
74,Big Bully,15000000,None
75,Screamers,20000000,None
76,Nico Icon,0,None
77,The Crossing Guard,0,$9 million
78,The Juror,44000000,$44 million [ 1 ]
79,The White Balloon,0,None
80,Things to Do in Denver When You're Dead,8000000,$8 million [ citation needed ]
81,Antonia's Line,900000,£1.5 million [ 1 ]
82,Once Upon a Time... When We Were Colored,0,None
83,Last Summer in the Hamptons,0,None
84,Angels and Insects,0,None
85,White Squall,38000000,None
86,Dunston Checks In,16000000,$20 million [ 3 ]
87,Black Sheep,0,None
88,Nick of Time,8169363,None
89,The Journey of August King,0,None
90,Mary Reilly,47000000,None
91,Vampire in Brooklyn,14000000,$14 million [ 1 ]
92,Beautiful Girls,0,None
93,Broken Arrow,50000000,None
94,A Midwinter's Tale,0,None
95,La Haine,3000000,€2.6 million [ 1 ]
96,Shopping,0,None
97,Heidi Fleiss: Hollywood Madam,0,None
98,City Hall,0,None
99,Bottle Rocket,7000000,$5 million [ 2 ]
100,Mr. Wrong,0,None
101,Unforgettable,18000000,None
102,Happy Gilmore,12000000,$12 million [ 1 ]
103,The Bridges of Madison County,24000000,None
104,Nobody Loves Me,0,None
105,Muppet Treasure Island,0,None
106,Catwalk,0,None
107,Headless Body in Topless Bar,0,"$400,000"
108,Braveheart,72000000,$53–72 million
109,Taxi Driver,1300000,$1.9 million [ 3 ] [ 4 ]
110,Rumble in the Bronx,7500000,US$7.5−13 million [ 4 ] [ 5 ]
111,Before and After,35000000,None
112,Margaret's Museum,0,None
113,Happiness Is in the Field,13365000,$10.2 million
114,Anne Frank Remembered,0,None
115,The Young Poisoner's Handbook,0,None
116,If Lucy Fell,0,$5 million
117,Steal Big Steal Little,25000000,$35 million
118,Race the Sun,0,None
119,The Boys of St. Vincent,0,None
120,Boomerang,40000000,None
121,Chungking Express,0,None
122,The Star Maker,0,None
123,Flirting with Disaster,7000000,None
124,The Neverending Story III: Escape from Fantasia,17000000,None
125,The Silences of the Palace,0,None
126,Jupiter's Wife,0,None
127,Pie in the Sky,0,None
128,Angela,0,None
129,Frankie Starlight,0,None
130,Jade,50000000,None
131,Nueba Yol,0,None
132,Sonic Outlaws,0,None
133,Down Periscope,0,$31 million [ 1 ]
134,From the Journals of Jean Seberg,0,None
135,Man of the Year,0,None
136,The Neon Bible,0,None
138,Up Close & Personal,60000000,None
139,The Birdcage,31000000,$31 million [ 1 ]
140,Virgin Mary,0,None
141,The Brothers McMullen,0,"$25,000 (Sundance showing) $238,000 (full rele..."
142,Bad Boys,19000000,None
143,The Amazing Panda Adventure,0,None
144,The Basketball Diaries,0,None
145,An Awfully Big Adventure,4000000,$4 million
146,Amateur,0,None
147,Apollo 13,52000000,None
148,Rob Roy,28000000,None
149,The Addiction,0,None
150,Batman Forever,100000000,$100 million [ 4 ]
151,Belle de Jour,0,None
152,Beyond Rangoon,0,$23 million [ 4 ]
153,Blue in the Face,2000000,$2 million
154,Canadian Bacon,11000000,$11 million [ 3 ]
155,Casper,50000000,None
156,Clockers,25000000,None
157,Congo,50000000,None
158,Crimson Tide,53000000,None
159,Crumb,0,None
160,Desperado,7000000,None
161,Devil in a Blue Dress,27000000,None
162,Die Hard: With a Vengeance,90000000,$90 million [ 5 ]
163,The Doom Generation,0,"$800,000"
164,Feast of July,0,$7.5 million [ 1 ]
165,First Knight,55000000,$55 million
166,Free Willy 2 - The Adventure Home,0,None
167,Hackers,20000000,None
168,Jeffrey,0,None
169,Johnny Mnemonic,25000000,None
170,Judge Dredd,90000000,None
171,Jury Duty,0,None
172,Kids,1500000,None
173,Living in Oblivion,500000,$500.000
174,Lord of Illusions,0,$11 million [ 2 ]
175,Love & Human Remains,0,None
176,Mad Love,0,None
177,Mallrats,6000000,$6.1 million
178,Mighty Morphin Power Rangers: The Movie,15000000,$15 million [ citation needed ]
179,Moonlight and Valentino,0,$9 million [ 2 ]
180,Mute Witness,2,None
181,Nadja,0,None
182,The Net,22000000,None
183,Nine Months,0,None
184,Party Girl,150000,None
185,The Prophecy,8,None
186,Reckless,0,None
187,Safe,0,None
188,The Scarlet Letter,50000000,None
189,Showgirls,45000000,$40-$45 million [ 5 ] [ 6 ]
190,Smoke,7000000,None
191,Something to Talk About,0,None
192,Species,35000000,None
193,The Stars Fell on Henrietta,0,$13 million
194,Strange Days,42000000,None
195,The Umbrellas of Cherbourg,0,$0.2 million [ 1 ]
196,The Tie That Binds,14000000,None
197,Three Wishes,0,None
198,Total Eclipse,0,None
199,"To Wong Foo, Thanks for Everything! Julie Newmar",0,$30 million [ 2 ]
200,Under Siege 2: Dark Territory,60000000,$60 million [ 1 ] [ 2 ]
201,Unstrung Heroes,0,None
202,Unzipped,0,None
203,A Walk in the Clouds,20000000,$20 million
204,Waterworld,175000000,$172–175 million [ 2 ] [ 3 ]
205,White Man's Burden,8000000,None
206,Wild Bill,30000000,None
207,The Browning Version,0,None
208,Bushwhacked,0,None
209,Burnt by the Sun,2800000,$3.6 million [ 1 ]
210,Before the Rain,0,None
211,Before Sunrise,2500000,$2.5 million [ 4 ]
212,Billy Madison,10000000,$10 million [ 1 ]
213,The Babysitter,0,None
214,Boys on the Side,21000000,$21 million [ 2 ]
215,The Cure,0,None
216,Castle Freak,0,None
217,Circle of Friends,0,None
218,Clerks,27000,None
219,Don Juan DeMarco,25000000,$25 million [ 1 ]
220,Disclosure,55000000,None
221,Dream Man,0,None
222,Drop Zone,45000000,None
223,Destiny Turns on the Radio,0,None
224,Death and the Maiden,0,None
225,Dolores Claiborne,0,None
226,Dumb and Dumber,16000000,$17 million [ 3 ]
227,Eat Drink Man Woman,0,None
228,Exotica,0,None
229,Exit to Eden,0,None
230,Ed Wood,18000000,None
231,French Kiss,0,None
232,Forget Paris,0,$21 million
233,Far from Home: The Adventures of Yellow Dog,0,None
234,A Goofy Movie,0,$18 million
235,Hideaway,15000000,None
236,Fluke,0,None
237,Farinelli,0,None
238,Gordy,0,$6–7 million [ 1 ]
240,The Glass Shield,0,None
241,Hoop Dreams,700000,"$700,000 [ 2 ]"
242,Heavenly Creatures,5000000,$5 million [ 2 ]
243,Houseguest,10500000,"$10,500,000"
244,Immortal Beloved,120,None
245,Heavyweights,0,$10 million [ 1 ]
246,The Hunted,0,None
247,I.Q.,25000000,None
248,Interview with the Vampire,60000000,None
249,Jefferson in Paris,14000000,$14 million
250,The Jerky Boys,0,None
251,Junior,60000000,None
252,Just Cause,0,None
253,A Kid in King Arthur's Court,0,$15 million
254,Kiss of Death,40000000,None
255,Star Wars,11000000,None
256,Little Women,18000000,None
257,A Little Princess,17000000,None
258,Ladybird Ladybird,0,None
259,L'Enfer,10000000,None
260,Like Water for Chocolate,2000000,None
261,Legends of the Fall,30000000,$30 million [ 1 ]
262,Major Payne,0,None
263,Little Odessa,0,None
264,Mi Vida Loca,0,None
265,Love Affair,60000000,None
266,Losing Isaiah,17000000,$16 million [ 1 ]
267,The Madness of King George,0,None
268,Mary Shelley's Frankenstein,45000000,None
269,Man of the House,0,None
270,Mixed Nuts,15000000,$20 million [ 1 ]
271,Milk Money,0,None
272,Miracle on 34th Street,0,"$248,000 [ 1 ]"
273,Miami Rhapsody,6,$6 million
274,My Family,5500000,None
275,Murder in the First,0,None
276,Nobody's Fool,0,None
277,Nell,31000000,None
278,New Jersey Drive,0,$5 million [ 1 ]
279,New York Cop,0,None
280,Beyond Bedlam,4800000,None
281,Nemesis 2 - Nebula,0,None
282,Nina Takes a Lover,0,"$600,000 [ 4 ]"
283,Natural Born Killers,34000000,$34 million [ 2 ]
284,Only You,0,None
285,Once Were Warriors,0,None
286,Poison Ivy II: Lily,0,None
287,Outbreak,50000000,None
288,Leon: The Professional,16000000,$16 million [ 4 ]
289,The Perez Family,11000000,"$11,000,000 (estimated)"
290,A Pyromaniac's Love Story,0,None
291,Pulp Fiction,8000000,$8–8.5 million [ 2 ] [ a ]
292,Panther,0,None
293,Pushing Hands,400000,None
294,Priest,0,None
295,Quiz Show,0,None
296,Picture Bride,0,None
297,Queen Margot,0,None
298,The Quick and the Dead,32000000,None
299,Roommates,22000000,None
300,Prêt-à-Porter,15000000,None
301,Three Colors: Red,0,None
302,Three Colors: Blue,0,None
303,Three Colors: White,0,None
304,"Red Firecracker, Green Firecracker",0,None
305,Rent-a-Kid,0,None
306,Relative Fear,0,None
307,Stuart Saves His Family,0,$12 million [ 1 ]
308,The Swan Princess,35000000,$21 million [ 2 ]
309,The Secret of Roan Inish,0,$5.7 million [ 1 ]
310,The Specialist,45000000,$45 million [ 1 ]
311,Stargate,55000000,None
312,The Santa Clause,22000000,$22 million [ 1 ]
313,The Shawshank Redemption,25000000,$25 million [ 2 ]
314,Shallow Grave,0,None
315,Suture,0,None
316,Strawberry and Chocolate,0,None
317,Swimming with Sharks,0,"$700,000 [ 1 ]"
318,The Sum of Us,32,None
319,Senior Trip,0,None
320,To Live,0,None
321,Tank Girl,25000000,None
322,Tales from the Crypt: Demon Knight,0,$12 million [ 3 ]
323,Star Trek: Generations,38000000,$35 million [ 3 ]
324,Tales from the Hood,6000000,$6 million
325,Tom & Viv,0,$7 million [ 1 ]
326,Village of the Damned,0,None
327,Tommy Boy,0,$20 million [ 2 ]
328,Vanya on 42nd Street,0,None
329,The Underneath,6500000,None
330,The Walking Dead,0,None
331,What's Eating Gilbert Grape,11000000,$11 million [ 2 ]
332,Virtuosity,30000000,$30 million
333,While You Were Sleeping,17000000,None
334,The War,0,None
335,Double Happiness,0,None
336,Muriel's Wedding,3000000,$9 million [ 3 ]
337,The Baby-Sitters Club,0,None
338,Ace Ventura: Pet Detective,15000000,$15 million [ 1 ]
339,"The Adventures of Priscilla, Queen of the Desert",0,"A$1,884,200 / (US$1,375,466)"
340,Backbeat,0,None
341,Bitter Moon,5000000,None
342,Bullets Over Broadway,0,$20 million [ 1 ]
343,Clear and Present Danger,62000000,None
344,The Client,45000000,None
345,"Corrina, Corrina",0,None
346,Crooklyn,0,$14 million [ 1 ]
347,The Crow,15000000,None
348,Cobb,0,None
349,The Flintstones,46000000,None
350,Forrest Gump,55000000,$55 million [ 2 ]
351,Four Weddings and a Funeral,6000000,£3 million [ 1 ] ($4.4 million [ 2 ] )
352,Higher Learning,0,None
353,I Like It Like That,0,None
354,I Love Trouble,45000000,None
355,It Could Happen to You,0,None
356,The Jungle Book,0,None
357,"The Wonderful, Horrible Life of Leni Riefenstahl",0,None
358,The Lion King,45000000,$45 million [ 2 ]
359,Little Buddha,35000000,$35 million [ citation needed ] [ inconsistent ]
360,New Nightmare,14000000,$8 million [ 2 ]
361,The Mask,23000000,None
362,Maverick,0,None
363,Mrs. Parker and the Vicious Circle,0,$7 million [ 1 ]
364,The Naked Gun 33⅓: The Final Insult,30000000,$30 million [ 2 ]
365,The Paper,6000000,None
366,Reality Bites,11500000,$11.5 million [ 3 ]
367,Red Rock West,8000000,$7 million
368,Ri¢hie Ri¢h,40000000,None
369,Safe Passage,0,None
370,The River Wild,45000000,$45 million [ 1 ] [ 2 ]
371,Speed,30000000,None
372,Speechless,0,None
373,Timecop,27000000,$27-28 million [ 2 ] [ 3 ]
374,True Lies,115000000,$100 [ 5 ] [ 6 ] –120 [ 7 ] million
375,When a Man Loves a Woman,0,None
376,Wolf,0,None
377,Wyatt Earp,63000000,None
378,Bad Company,0,None
379,A Man of No Importance,0,None
380,S.F.W.,0,None
381,A Low Down Dirty Shame,10000000,None
382,"Boys Life: Three Stories of Love, Lust, and Li...",0,None
383,Colonel Chabert,0,None
384,"Faster, Pussycat! Kill! Kill!",45000,"$45,000 [ 2 ]"
385,Jason's Lyric,7000000,$7 million
386,The Secret Adventures of Tom Thumb,0,None
387,Street Fighter,35000000,None
388,Coldblooded,0,None
389,Desert Winds,0,None
390,Fall Time,0,$4 million
391,The Fear,0,None
393,Girl in the Cadillac,0,None
394,Homage,0,None
395,Mirage,0,None
396,Open Season,0,None
397,Dos Crímenes,0,None
398,Brother Minister: The Assassination of Malcolm X,0,None
399,Highlander: The Final Dimension,26000000,$26 [ 3 ] –34 [ 4 ] [ 5 ] million
400,Federal Hill,0,None
401,In the Mouth of Madness,8000000,$8 million [ 1 ]
402,8 Seconds,0,$7 million [ 1 ]
403,Above the Rim,0,$6.5 million
404,Addams Family Values,0,$47 million [ 1 ]
405,Martin Lawrence: You So Crazy,0,None
406,The Age of Innocence,34000000,None
407,Airheads,0,$15 million [ 1 ]
408,The Air Up There,17080000,$17 million
409,Another Stakeout,0,$30 million
410,Bad Girls,0,None
411,Barcelona,3200000,€3.6 billion [ 7 ]
412,Being Human,40000000,None
413,The Beverly Hillbillies,0,None
414,Beverly Hills Cop III,50000000,$40–70 million [ 2 ] [ 3 ] [ 4 ]
415,Black Beauty,0,None
416,Blink,0,None
417,Blown Away,0,None
418,Blue Chips,0,$35 million
419,Blue Sky,0,None
420,Body Snatchers,13000000,None
421,Boxing Helena,0,None
422,A Bronx Tale,22000000,$10 million [ 1 ]
423,Cabin Boy,0,$10 million
424,Calendar Girl,13000000,None
425,Carlito's Way,30000000,$30 million
426,City Slickers II: The Legend of Curly's Gold,0,$40 million [ 2 ]
427,Clean Slate,0,None
428,Cliffhanger,70000000,None
429,Coneheads,0,None
430,Color of Night,40000000,$40 million [ 1 ]
431,Cops & Robbersons,0,None
432,The Cowboy Way,0,None
433,Dangerous Game,0,None
434,Dave,0,None
435,Dazed and Confused,6900000,None
436,Demolition Man,57000000,None
438,Even Cowgirls Get the Blues,8000000,None
439,Fatal Instinct,0,None
440,Farewell My Concubine,0,None
441,The Favor,0,None
442,Fearless,0,None
443,Fear of a Black Hat,0,$1 million [ 1 ]
444,With Honors,0,None
445,Flesh and Bone,0,None
446,Widows' Peak,0,None
447,For Love or Money,30000000,None
448,The Firm,42000000,None
449,Free Willy,20000000,$20 million [ 1 ]
450,Fresh,0,None
451,The Fugitive,44000000,None
452,Geronimo: An American Legend,35000000,$35 million
453,The Getaway,0,None
454,Getting Even with Dad,30000000,$30 million [ citation needed ]
455,Go Fish,0,None
456,A Good Man in Africa,0,$18.5million [ 1 ]
457,Guilty as Sin,0,$12 million [ 1 ]
458,Hard Target,18000000,$19.5-20 million [ 1 ] [ 2 ]
459,Heaven & Earth,33000000,None
460,Hot Shots! Part Deux,25000000,$25 million
461,Live Nude Girls,0,None
462,The Englishman Who Went Up a Hill But Came Dow...,0,None
463,The House of the Spirits,25000000,None
464,House Party 3,0,None
465,The Hudsucker Proxy,30000000,$25 million [ 3 ]
466,I'll Do Anything,40000000,$40 million
467,In the Army Now,0,None
468,In the Line of Fire,40000000,$40 million [ 1 ] [ 2 ]
469,In the Name of the Father,13000000,$13 million
470,The Inkwell,0,$8 million [ 1 ]
471,What's Love Got to Do with It,0,None
472,Jimmy Hollywood,30000000,$30 million [ 1 ]
473,Judgment Night,0,None
474,Jurassic Park,63000000,$56–63 million
475,Kalifornia,9000000,$8.5 million [ 3 ]
476,Killing Zoe,1500000,$1.5 million [ 2 ]
477,King of the Hill,0,None
478,Lassie,0,None
479,Last Action Hero,85000000,$85 million [ 3 ]
480,Life With Mikey,0,None
481,Lightning Jack,0,None
482,M. Butterfly,0,None
483,Made in America,22000000,None
484,Malice,0,None
485,The Man without a Face,0,None
486,Manhattan Murder Mystery,13500000,$13.5 million ( est. )
487,Menace II Society,3500000,$3.5 million
488,Executive Decision,55000000,$55 million [ 1 ]
489,In the Realm of the Senses,0,None
490,What Happened Was...,0,None
491,Much Ado About Nothing,8000000,None
492,Mr. Jones,0,None
493,Mr. Wonderful,0,None
494,Mrs. Doubtfire,25000000,$25 million [ 2 ]
495,Naked,0,None
496,The Next Karate Kid,12000000,$12 million
497,The New Age,0,None
498,No Escape,20000000,None
499,North,40000000,None
500,Orlando,4000000,None
501,A Perfect World,30000000,$30 million [ 1 ]
502,Philadelphia,26000000,None
503,The Piano,7000000,US$7 million [ 4 ]

In [60]:
pd.set_option('display.max_rows', 500)

In [56]:
# Ton DataFrame à sauvegarder
# Exemple : df = pd.DataFrame({'col1': [1, 2], 'col2': ['a', 'b']})
BUCKET = 'mlepennec-ensae'

FILE_OUT_S3 = '/movies_export.csv'  # Chemin dans le bucket
FILE_OUT_PATH = BUCKET + FILE_OUT_S3       # Chemin complet S3

# Écriture vers S3
with fs.open(FILE_OUT_PATH, mode='w') as f_out:
    data.to_csv(f_out, index=False)

In [148]:

if r_url_film.status_code == 404:
    print("url simple ne fonctionne pas")
    liste_acteurs.append("impossible de récupérer la liste des acteurs")
else:
    print("pas erreur 404")
    soup_film = BeautifulSoup(r_url_film.text, "html.parser")

    selector_homonymie = "div:nth-child(2) > p > a"
    homonymie = soup_film.select(selector_homonymie)

    if homonymie[0].text=='page d’homonymie':
        print("homonymie")
        url_film = data_movies_df.url_film_date[i]
        
        r_url_film = requests.get(url_film)

        if r_url_film.status_code == 404:
            print("url avec film et annee ne fonctionne pas")
            url_film = data_movies_df.url_film[i]
            r_url_film = requests.get(url_film)

            if r_url_film.status_code == 404:
                print("url avec annee ne fonctionne pas")
                liste_acteurs.append("impossible de récupérer la liste des acteurs")
            else:
                soup_film = BeautifulSoup(r_url_film.text, "html.parser")

                selector_film = "div.infobox_v3 table tr td div p"
                acteurs = soup_film.select(selector_film)
        
                liste_acteurs.append(acteurs[0].text)
    else:
        print("pas d'homonymie")
        soup_film = BeautifulSoup(r_url_film.text, "html.parser")

        selector_film = "div.infobox_v3 table tr td div p"
        acteurs = soup_film.select(selector_film)
        if len(acteurs)==0:
            print("essai d'autres url")
            url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film,_" + data.release_date[i][0:4] + ")"
        
            r_url_film = requests.get(url_film)

            if r_url_film.status_code == 404:

                url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film)"
                r_url_film = requests.get(url_film)

                if r_url_film.status_code == 404:

                    liste_acteurs.append("impossible de récupérer la liste des acteurs")
                else:
                    soup_film = BeautifulSoup(r_url_film.text, "html.parser")

                    selector_film = "div.infobox_v3 table tr td div p"
                    acteurs = soup_film.select(selector_film)
        
                    liste_acteurs.append(acteurs[0].text)
        else:
            liste_acteurs.append(acteurs[0].text)

pas erreur 404
homonymie

In [183]:
url_film

'https://fr.wikipedia.org/wiki/Balto_(film)'

In [135]:
url_wikipedia = "https://fr.wikipedia.org/wiki/"
liste_acteurs=[]
for i in range(100):
    print(i)
    url_film = url_wikipedia + data.title[i].replace(" ", "_")

    r_url_film = requests.get(url_film, headers = headers)
    if r_url_film.status_code == 404:
        liste_acteurs.append("impossible de récupérer la liste des acteurs")
    else:
        soup_film = BeautifulSoup(r_url_film.text, "html.parser")

        selector_film = "div div p a"
        acteurs = soup_film.select(selector_film)

        if acteurs[0].text=='page d’homonymie':
            url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film,_" + data.release_date[i][0:4] + ")"
        
            r_url_film = requests.get(url_film, headers = headers)

            if r_url_film.status_code == 404:

                url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film)"
                r_url_film = requests.get(url_film, headers = headers)

                if r_url_film.status_code == 404:

                    liste_acteurs.append("impossible de récupérer la liste des acteurs")
                else:
                    soup_film = BeautifulSoup(r_url_film.text, "html.parser")

                    selector_film = "div.infobox_v3 table tr td div p"
                    acteurs = soup_film.select(selector_film)
        
                    liste_acteurs.append(acteurs[0].text)
        else:
            soup_film = BeautifulSoup(r_url_film.text, "html.parser")

            selector_film = "div.infobox_v3 table tr td div p"
            acteurs = soup_film.select(selector_film)
            if len(acteurs)==0:
                print("essai d'autres url")
                url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film,_" + data.release_date[i][0:4] + ")"
        
                r_url_film = requests.get(url_film, headers = headers)

                if r_url_film.status_code == 404:

                    url_film = url_wikipedia + data.title[i].replace(" ", "_") + "_(film)"
                    r_url_film = requests.get(url_film, headers = headers)

                    if r_url_film.status_code == 404:

                        liste_acteurs.append("impossible de récupérer la liste des acteurs")
                    else:
                        soup_film = BeautifulSoup(r_url_film.text, "html.parser")

                        selector_film = "div.infobox_v3 table tr td div p"
                        acteurs = soup_film.select(selector_film)
        
                        liste_acteurs.append(acteurs[0].text)
            else:
                liste_acteurs.append(acteurs[0].text)

0

1
2
3
4
5
6
7
8
9
10
11
12
essai d'autres url
13
14
essai d'autres url
15
16
essai d'autres url
17
18
19
20
21
22
essai d'autres url
23
24
25
26
27
essai d'autres url
28
29
30
31
32
33
essai d'autres url
34
35
36
37
38
39
essai d'autres url
40
essai d'autres url
41
essai d'autres url
42

IndexError: list index out of range

In [136]:
liste_acteurs

['Tom HanksTim Allen\n',
 'impossible de récupérer la liste des acteurs',
 'Whitney Houston Angela BassettLoretta Devine  Lela Rochon\n',
 'impossible de récupérer la liste des acteurs',
 'impossible de récupérer la liste des acteurs',
 'impossible de récupérer la liste des acteurs',
 'Pierce BrosnanSean BeanIzabella ScorupcoFamke JanssenAlan Cumming\n',
 'Michael DouglasAnnette BeningMartin SheenMichael J. Fox\n',
 'impossible de récupérer la liste des acteurs',
 'Kevin BaconBob HoskinsBridget FondaJim CummingsPhil Collins\n',
 'Anthony HopkinsJoan AllenPowers BootheEd Harris\n',
 'Geena DavisMatthew Modine Frank LangellaMaury ChaykinPatrick Malahide\n',
 'Robert De NiroJoe PesciSharon Stone\n',
 'impossible de récupérer la liste des acteurs',
 'Tim Roth  Madonna  Valeria Golino  Jennifer Beals  Antonio Banderas\n',
 'Jim CarreyIan McNeiceSimon CallowBob GuntonMaynard Eziashi\n',
 'Wesley SnipesWoody HarrelsonJennifer LopezRobert Blake\n',
 'John TravoltaGene HackmanRene RussoDanny DeVito\n',
 'Sigourney WeaverHolly HunterDermot Mulroney\n',
 'Sylvester StalloneAntonio BanderasJulianne Moore\n',
 'Mary SteenburgenSean Patrick FlaneryLance HenriksenJeff Goldblum\n',
 'Nicolas CageElisabeth Shue\n',
 "Melanie Griffith, Demi Moore, Rosie O'Donnell, Rita Wilson\n",
 'impossible de récupérer la liste des acteurs',
 'Gong LiBaotian LiWang Xiaoxiao\n',
 'Michelle PfeifferWade DominguezRenoly SantiagoGeorge DzundzaCourtney B. Vance\n',
 'Bruce Willis Madeleine Stowe Brad Pitt Christopher Plummer David Morse\n',
 'impossible de récupérer la liste des acteurs',
 'Christine Cavanaugh (voix)  James Cromwell  Magda Szubanski\n',
 'Emma Thompson  Jonathan Pryce Steven Waddington\n',
 'impossible de récupérer la liste des acteurs',
 'impossible de récupérer la liste des acteurs',
 'George Newbern Leslie Hope Kimberly Foster\xa0(en) Barry Corbin\n',
 'Alicia SilverstoneStacey DashBrittany MurphyPaul Rudd\n',
 'impossible de récupérer la liste des acteurs']