In [ ]:
import os
import pandas as pd
import s3fs
import sklearn
import matplotlib.pyplot as plt

In [14]:
os.environ['AWS_S3_ENDPOINT']
S3_ENDPOINT_URL = 'http://' + os.environ['AWS_S3_ENDPOINT']
fs = s3fs.S3FileSystem(client_kwargs = {'endpoint_url' :S3_ENDPOINT_URL })
fs.ls('mlepennec-ensae')
BUCKET = 'mlepennec-ensae'
FILE_KEY_S3 = '/engieX.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    X_df = pd.read_csv(file_in,delimiter=';')

In [ ]:
FILE_KEY_S3 = '/engieY.csv'
FILE_PATH_S3 = BUCKET+FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode = "rb") as file_in : 
    y_df = pd.read_csv(file_in,delimiter=';')

NameError: name 'y' is not defined

In [19]:
y_df

            ID      TARGET
0            1    -0.70300
1            2    -0.74700
2            3    -0.79100
3            4    -0.73600
4            5    -1.05500
...        ...         ...
617381  617382  1151.82200
617382  617383  1119.93300
617383  617384  1223.82800
617384  617385  1086.55900
617385  617386  1142.92311

[617386 rows x 2 columns]

In [15]:
X_df

,ID,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,...,Rotor_speed,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c
0,1,WT3,1.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,294.19000,294.23999
1,2,WT3,2.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,297.82999,294.23999
2,3,WT3,3.0,92.470001,92.470001,92.470001,0.00,7.00,7.000000,7.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,322.20999,294.23999
3,4,WT3,4.0,92.470001,92.470001,92.470001,0.00,6.97,6.700000,7.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.400000,0.00,318.69000,294.23999
4,5,WT3,5.0,92.470001,92.470001,92.470001,0.00,6.93,6.000000,7.0,...,0.000000,0.00,0.000000,0.00,2.400000,2.400000,2.500000,0.00,314.89001,294.23999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617381,617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,...,16.930000,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000
617382,617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,...,16.969999,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000
617383,617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,...,17.040001,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000
617384,617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,...,16.860001,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000
617385,617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,...,17.100000,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000

In [30]:
df = X_df.merge(y_df, left_on='ID', right_on='ID')

In [40]:
WT1_df = df[df.MAC_CODE == 'WT1']
WT1_df

,ID,MAC_CODE,Date_time,Pitch_angle,Pitch_angle_min,Pitch_angle_max,Pitch_angle_std,Hub_temperature,Hub_temperature_min,Hub_temperature_max,...,Rotor_speed_min,Rotor_speed_max,Rotor_speed_std,Rotor_bearing_temperature,Rotor_bearing_temperature_min,Rotor_bearing_temperature_max,Rotor_bearing_temperature_std,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
462679,462680,WT1,1.0,92.410004,92.410004,92.410004,0.00,8.24,8.000000,9.0,...,0.00,0.000000,0.00,2.380000,2.300000,2.500000,0.06,301.44000,302.89999,-2.72700
462680,462681,WT1,2.0,92.410004,92.410004,92.410004,0.00,8.19,8.000000,9.0,...,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,299.73999,302.89999,-2.78200
462681,462682,WT1,3.0,92.410004,92.410004,92.410004,0.00,8.90,8.000000,9.0,...,0.00,0.000000,0.00,2.420000,2.300000,2.500000,0.07,332.13000,302.89999,-2.83700
462682,462683,WT1,4.0,92.410004,92.410004,92.410004,0.00,7.62,8.000000,9.0,...,0.00,0.000000,0.00,2.400000,2.300000,2.500000,0.07,322.01999,302.89999,-2.55100
462683,462684,WT1,5.0,92.410004,92.410004,92.410004,0.00,7.09,7.000000,8.0,...,0.00,0.000000,0.00,2.410000,2.300000,2.500000,0.07,322.75000,302.89999,-3.18900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617381,617382,WT1,157676.0,-1.010000,-1.010000,-0.840000,0.01,18.00,17.090000,18.0,...,14.79,17.379999,0.52,35.790001,35.700001,35.900002,0.02,229.27000,231.56000,1151.82200
617382,617383,WT1,157677.0,-1.010000,-1.010000,-1.010000,0.00,17.99,17.469999,18.0,...,15.39,17.389999,0.34,35.810001,35.599998,35.849998,0.06,227.53000,231.56000,1119.93300
617383,617384,WT1,157678.0,-0.810000,-1.010000,1.490000,0.58,18.00,17.770000,18.0,...,15.67,17.420000,0.30,36.060001,35.799999,36.099998,0.10,228.75000,231.56000,1223.82800
617384,617385,WT1,157679.0,-1.000000,-1.010000,-0.620000,0.03,18.00,17.700001,18.0,...,14.86,17.340000,0.60,36.189999,36.099998,36.200001,0.05,226.16000,231.56000,1086.55900
617385,617386,WT1,157680.0,-0.910000,-1.010000,1.080000,0.42,18.00,18.000000,18.0,...,16.17,17.389999,0.15,36.240002,36.200001,36.400002,0.06,226.06000,231.56000,1142.92311

In [41]:
WT1_df.columns

Index(['ID', 'MAC_CODE', 'Date_time', 'Pitch_angle', 'Pitch_angle_min',
       'Pitch_angle_max', 'Pitch_angle_std', 'Hub_temperature',
       'Hub_temperature_min', 'Hub_temperature_max', 'Hub_temperature_std',
       'Generator_converter_speed', 'Generator_converter_speed_min',
       'Generator_converter_speed_max', 'Generator_converter_speed_std',
       'Generator_speed', 'Generator_speed_min', 'Generator_speed_max',
       'Generator_speed_std', 'Generator_bearing_1_temperature',
       'Generator_bearing_1_temperature_min',
       'Generator_bearing_1_temperature_max',
       'Generator_bearing_1_temperature_std',
       'Generator_bearing_2_temperature',
       'Generator_bearing_2_temperature_min',
       'Generator_bearing_2_temperature_max',
       'Generator_bearing_2_temperature_std', 'Generator_stator_temperature',
       'Generator_stator_temperature_min', 'Generator_stator_temperature_max',
       'Generator_stator_temperature_std', 'Gearbox_bearing_1_temperature',
       'Gearbox_bearing_1_temperature_min',
       'Gearbox_bearing_1_temperature_max',
       'Gearbox_bearing_1_temperature_std', 'Gearbox_bearing_2_temperature',
       'Gearbox_bearing_2_temperature_min',
       'Gearbox_bearing_2_temperature_max',
       'Gearbox_bearing_2_temperature_std', 'Gearbox_inlet_temperature',
       'Gearbox_inlet_temperature_min', 'Gearbox_inlet_temperature_max',
       'Gearbox_inlet_temperature_std', 'Gearbox_oil_sump_temperature',
       'Gearbox_oil_sump_temperature_min', 'Gearbox_oil_sump_temperature_max',
       'Gearbox_oil_sump_temperature_std', 'Nacelle_angle',
       'Nacelle_angle_min', 'Nacelle_angle_max', 'Nacelle_angle_std',
       'Nacelle_temperature', 'Nacelle_temperature_min',
       'Nacelle_temperature_max', 'Nacelle_temperature_std',
       'Absolute_wind_direction', 'Outdoor_temperature',
       'Outdoor_temperature_min', 'Outdoor_temperature_max',
       'Outdoor_temperature_std', 'Grid_frequency', 'Grid_frequency_min',
       'Grid_frequency_max', 'Grid_frequency_std', 'Grid_voltage',
       'Grid_voltage_min', 'Grid_voltage_max', 'Grid_voltage_std',
       'Rotor_speed', 'Rotor_speed_min', 'Rotor_speed_max', 'Rotor_speed_std',
       'Rotor_bearing_temperature', 'Rotor_bearing_temperature_min',
       'Rotor_bearing_temperature_max', 'Rotor_bearing_temperature_std',
       'Absolute_wind_direction_c', 'Nacelle_angle_c', 'TARGET'],
      dtype='object')

In [42]:
WT1_df = WT1_df.drop(columns=[col for col in WT1_df.columns if col.endswith("min") or col.endswith("max") or col.endswith('std')])

In [43]:
WT1_df = WT1_df[WT1_df.Date_time % 6 == 1]
WT1_df

,ID,MAC_CODE,Date_time,Pitch_angle,Hub_temperature,Generator_converter_speed,Generator_speed,Generator_bearing_1_temperature,Generator_bearing_2_temperature,Generator_stator_temperature,...,Nacelle_temperature,Absolute_wind_direction,Outdoor_temperature,Grid_frequency,Grid_voltage,Rotor_speed,Rotor_bearing_temperature,Absolute_wind_direction_c,Nacelle_angle_c,TARGET
462679,462680,WT1,1.0,92.410004,8.240000,3.92,0.1700,7.700000,6.840000,4.900000,...,4.890000,301.440000,-0.70,49.980000,684.19000,0.000000,2.380000,301.440000,302.899990,-2.727000
462685,462686,WT1,7.0,92.410004,6.830000,3.93,0.1700,7.700000,6.850000,4.780000,...,4.840000,303.250000,-0.74,0.000000,0.00000,0.000000,2.320000,303.250000,302.899990,0.100000
462695,462696,WT1,673.0,92.410004,2.000000,4.26,0.0000,-1.690000,-2.640000,-2.600000,...,2.010000,84.379997,-3.40,50.000000,688.29999,0.000000,-2.100000,84.379997,301.810000,-4.993000
462701,462702,WT1,679.0,92.410004,3.960000,4.09,0.0600,-0.230000,-1.350000,-2.480000,...,2.180000,76.830002,-3.74,49.959999,686.22998,0.000000,-2.080000,76.830002,79.000000,-4.542000
462707,462708,WT1,685.0,92.410004,4.000000,4.46,0.4300,0.750000,-0.500000,-2.280000,...,2.200000,59.270000,-4.00,49.990002,684.65002,0.000000,-2.020000,59.270000,69.120003,-3.145000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
617356,617357,WT1,157651.0,-1.000000,18.000000,1792.59,1794.8400,32.400002,36.439999,59.680000,...,19.240000,239.500000,10.20,50.020000,698.78998,17.090000,35.730000,239.500000,239.250000,1230.637000
617362,617363,WT1,157657.0,-1.000000,17.760000,1776.84,1779.0601,36.270000,37.509998,59.470001,...,20.020000,234.899990,10.38,50.000000,699.76001,16.940001,35.750000,234.899990,239.250000,1057.122989
617368,617369,WT1,157663.0,-1.000000,17.510000,1767.27,1769.4900,40.720001,40.349998,63.099998,...,19.469999,230.570010,10.41,50.000000,698.97998,16.850000,35.599998,230.570010,227.170000,998.240022
617374,617375,WT1,157669.0,-1.000000,17.549999,1775.65,1777.9100,42.040001,40.750000,63.630001,...,20.170000,224.090000,10.51,50.029999,701.15997,16.930000,35.709999,224.090000,237.970000,1066.154011
617380,617381,WT1,157675.0,-1.000000,18.000000,1787.27,1789.5200,41.360001,40.570000,63.810001,...,20.480000,231.590000,10.45,50.009998,696.65002,17.040001,35.889999,231.590000,231.560000,1147.015000

In [44]:
for col in WT1_df.columns:
    n_na=WT1_df[col].isna().sum()
    if n_na > 0:
        print(f"{col} : {n_na}")

Generator_converter_speed : 336
Gearbox_inlet_temperature : 336
Grid_voltage : 4949
Absolute_wind_direction_c : 3
Nacelle_angle_c : 3

In [45]:
WT1_df = WT1_df.drop(columns=["Generator_converter_speed", "Gearbox_inlet_temperature", "Grid_voltage", "Absolute_wind_direction_c", "Nacelle_angle_c", "Date_time", 'ID', 'MAC_CODE'])

In [50]:
WT1_df = WT1_df.reset_index(drop=True)
WT1_df

,Pitch_angle,Hub_temperature,Generator_speed,Generator_bearing_1_temperature,Generator_bearing_2_temperature,Generator_stator_temperature,Gearbox_bearing_1_temperature,Gearbox_bearing_2_temperature,Gearbox_oil_sump_temperature,Nacelle_angle,Nacelle_temperature,Absolute_wind_direction,Outdoor_temperature,Grid_frequency,Rotor_speed,Rotor_bearing_temperature,TARGET
0,92.410004,8.240000,0.1700,7.700000,6.840000,4.900000,2.390000,2.420000,2.100000,302.899990,4.890000,301.440000,-0.70,49.980000,0.000000,2.380000,-2.727000
1,92.410004,6.830000,0.1700,7.700000,6.850000,4.780000,2.300000,2.330000,2.110000,302.899990,4.840000,303.250000,-0.74,0.000000,0.000000,2.320000,0.100000
2,92.410004,2.000000,0.0000,-1.690000,-2.640000,-2.600000,-1.900000,-1.300000,1.750000,301.810000,2.010000,84.379997,-3.40,50.000000,0.000000,-2.100000,-4.993000
3,92.410004,3.960000,0.0600,-0.230000,-1.350000,-2.480000,-1.700000,-1.200000,0.840000,79.000000,2.180000,76.830002,-3.74,49.959999,0.000000,-2.080000,-4.542000
4,92.410004,4.000000,0.4300,0.750000,-0.500000,-2.280000,-1.600000,-1.010000,0.170000,69.120003,2.200000,59.270000,-4.00,49.990002,0.000000,-2.020000,-3.145000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25757,-1.000000,18.000000,1794.8400,32.400002,36.439999,59.680000,71.739998,72.290001,52.220001,239.250000,19.240000,239.500000,10.20,50.020000,17.090000,35.730000,1230.637000
25758,-1.000000,17.760000,1779.0601,36.270000,37.509998,59.470001,70.470001,71.230003,51.360001,239.250000,20.020000,234.899990,10.38,50.000000,16.940001,35.750000,1057.122989
25759,-1.000000,17.510000,1769.4900,40.720001,40.349998,63.099998,69.209999,71.980003,56.939999,227.170000,19.469999,230.570010,10.41,50.000000,16.850000,35.599998,998.240022
25760,-1.000000,17.549999,1777.9100,42.040001,40.750000,63.630001,62.869999,71.040001,55.990002,237.970000,20.170000,224.090000,10.51,50.029999,16.930000,35.709999,1066.154011
25761,-1.000000,18.000000,1789.5200,41.360001,40.570000,63.810001,64.970001,72.110001,57.080002,231.560000,20.480000,231.590000,10.45,50.009998,17.040001,35.889999,1147.015000

In [70]:
cv_thres = 0.8*len(WT1_df)
X = WT1_df.drop(columns = ['TARGET'])
Y = WT1_df['TARGET']
X_train = X[X.index < cv_thres].copy()
X_test = X[X.index >= cv_thres].copy()
Y_train = Y[Y.index < cv_thres].copy()
Y_test = Y[Y.index >= cv_thres].copy()

In [54]:
X_train.shape

(20610, 16)

In [55]:
X_test.shape

(5152, 16)

In [56]:
Y_train.shape

(20610,)

In [58]:
Y_test.shape

(5152,)

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, ElasticNetCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

In [ ]:
simple_lm_model = LinearRegression().fit(X_train, Y_train)

# Erreur d'entraînement
print(mean_absolute_error(simple_lm_model.predict(X_train), Y_train))

# Erreur de test
print(mean_absolute_error(simple_lm_model.predict(X_test), Y_test))

102.26755121236634
109.64214850907149

In [ ]:
random_forest = RandomForestRegressor(n_estimators=100, random_state=42).fit(X_train, Y_train)

print(mean_absolute_error(random_forest.predict(X_train), Y_train))

print(mean_absolute_error(random_forest.predict(X_test), Y_test))

7.674067759117004
20.742648236486954

In [79]:
grad_boost = GradientBoostingRegressor(random_state=42).fit(X_train, Y_train)

print(mean_absolute_error(grad_boost.predict(X_train), Y_train))

print(mean_absolute_error(grad_boost.predict(X_test), Y_test))

22.84748200217355
23.772453578049564